version: '3.7'
name: school
services:
  #  # Reverse Proxy
  #  nginx:
  #    image: nginx:mainline-alpine
  #    container_name: nginx
  #    restart: unless-stopped
  #    ports:
  #      - 8080:80
  #      - 8443:443
  #    volumes:
  #      - ./storage/logs/:/var/log/nginx
  #      - ./nginx/conf.d/:/etc/nginx/conf.d/
  #
  #
  # The Database
  # database:
  #   container_name: mysql_database
  #   image: mariadb:10.8.3
  #   restart: always
  #   volumes:
  #     - dbdata:/var/lib/mysql
  #     - ./init:/docker-entrypoint-initdb.d
  #   environment:
  #     MYSQL_DATABASE: db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: example
  #     MYSQL_ROOT_PASSWORD: example
  #   ports:
  #     - 33067:3306
  #   networks:
  #     - school-network

  # phpmyadmin:
  #   container_name: phpmyadmin
  #   depends_on:
  #     - database
  #   image: phpmyadmin:5.2.0
  #   restart: always
  #   ports:
  #     - 5801:80
  #   environment:
  #     PMA_USER: root
  #     PMA_PASSWORD: example
  #     PMA_HOST: database
  #     MYSQL_ROOT_PASSWORD: example
  #   networks:
  #     - school-network
  mongo:
    image: arm64v8/mongo:3.6.23
    restart: always
    volumes:
      - /Users/gavin/Desktop/Task3:/Task3
    networks:
      - school-network

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - school-network
    
volumes:
  dbdata:
networks:
  nginx-proxy:
    external: true
    name: nginx-proxy
  school-network:
    driver: bridge
