SPOOL solution1a.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

--SELECT P_BRAND, P_TYPE, P_RETAILPRICE FROM PART;

SELECT COUNT(*) FROM PART
WHERE P_BRAND = 'BRAND#18';

--CREATE INDEX id2 ON PART(P_BRAND);
--DROP INDEX id2;

SELECT L_ORDERKEY, COUNT(*) FROM LINEITEM
WHERE L_ORDERKEY = 1184000
GROUP BY L_ORDERKEY;

--CREATE INDEX id3 ON LINEITEM(L_ORDERKEY);
--DROP INDEX id3;

SELECT MAX(PS_SUPPKEY) FROM PARTSUPP;

--CREATE INDEX id4 ON PARTSUPP(PS_SUPPKEY);
--DROP INDEX id4;

SELECT PS_SUPPKEY, PS_PARTKEY, PS_SUPPLYCOST FROM PARTSUPP
WHERE PS_SUPPKEY = 3699
AND PS_PARTKEY = 700;

--CREATE INDEX id5 ON PARTSUPP(PS_SUPPKEY, PS_PARTKEY);
--DROP INDEX id5;

SPOOL OFF
